Account modal
Patrik93JS/ToDoApp pull request #6
Opened 2023-06-20 16:09 UTC by Patrik93JS

2023-06-20 16:23 UTC, cplprince requested changes
👎

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/app/layout.tsx
> +  ("/registration");
wut??? nemělo by to bát pole ????

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/app/layout.tsx
> +  const hideLayout = usePathname().includes(withoutLayout);
Celé to máš vzhuru nohama. Zamysli si nad tou logikou.

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/components/loginForm/LoginForm.tsx
> +  const userPat = useMeMutation();
???? trochu hovadina ne? :D useMeMutation vrací pole, první index mutace, druhý index je objekt attribut.

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/components/loginForm/LoginForm.tsx
> +    console.log("haf", userPat); // TODO nefunguje
jasně že nefunguje když tak vložíš celé pole

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/store/slices/authSlice.ts
tohle celé zruš

2023-06-20 16:23 UTC, cplprince commented on FE/todo-app/src/types/Auth.ts
> +};
co si vybavuju tak response je mnohem větší jak 3 řádky. Dávej všude kompletní responsy, a ne jen to co se ti líbí.

2023-06-20 17:42 UTC, Patrik93JS commented on FE/todo-app/src/app/layout.tsx
> +  ("/registration");
jsem kokot :)

2023-06-21 10:48 UTC, cplprince requested changes
🥇

2023-06-21 10:48 UTC, cplprince commented on FE/todo-app/src/store/reducers.ts
> +// import { authSlice } from "./slices/authSlice";
vymazat, už neexistuje

2023-06-21 10:48 UTC, cplprince commented on FE/todo-app/src/store/reducers.ts
> +  // [authSlice.name]: authSlice.reducer,
vymazat, už neexistuje

2023-06-21 10:51 UTC, merged